export const CartActions = {
  APPEND_ITEM: 'APPEND_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  DECREMENT_ITEM: 'DECREMENT_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  ADD_ADDRESS: 'ADD_ADDRESS',
  ADD_APTHOU: 'ADD_APTHOU',
  ADD_PROVINCE: 'ADD_PROVINCE',
  ADD_REFERENCES: 'ADD_REFERENCES',
  ADD_ADITIONALDESC: 'ADD_ADITIONALDESC',
};
