export const ordersActions = {
  LOAD_ORDERS: 'LOAD_ORDERS',
  LOAD_ORDERS_SUCCESS: 'LOAD_ORDERS_SUCCESS',
  LOAD_ORDERS_ERROR: 'LOAD_ORDERS_ERROR',

  LOAD_SAVE_ORDER: 'LOAD_SAVE_ORDER',
  LOAD_SAVE_ORDER_SUCCESS: 'LOAD_SAVE_ORDER_SUCCESS',
  LOAD_SAVE_ORDER_ERROR: 'LOAD_SAVE_ORDER_ERROR',

  DELETE_ORDER: 'DELETE_ORDER',
  DELETE_ORDER_SUCCESS: 'DELETE_ORDER_SUCCESS',
  DELETE_ORDER_ERROR: 'DELETE_ORDER_ERROR',
};
